/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tallerplus.interfaz;

import com.tallerplus.files.Ficheros;
import com.tallerplus.gestion.GestionCitas;
import com.tallerplus.gestion.GestionClientes;
import com.tallerplus.objetos.Cita;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dani_
 */
public class BuscarCita extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Creates new form BuscarCita
     */
    public BuscarCita() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        //Columnas de la tabla
        tabla.addColumn("Matrícula");
        tabla.addColumn("Fecha y hora");
        tabla.addColumn("Descripción");
        tabla.addColumn("Precio");
        tabla.addColumn("Estado");

        ArrayList<Cita> citas = new ArrayList();

        citas = Ficheros.citas;
        Collections.sort(citas);
        Iterator<Cita> it = citas.iterator();
        while (it.hasNext()) {
            Cita cita = it.next();
            if (!(cita.getEstado().equalsIgnoreCase("pendiente") || cita.getEstado().equalsIgnoreCase("en proceso"))) {
                it.remove();
            }
        }
        for (Cita elemento : citas) {
            String anadir[] = new String[5];
            anadir[0] = elemento.getMatricula();
            anadir[1] = elemento.getFechaHora();
            anadir[2] = elemento.getDescripcion();
            anadir[3] = Float.toString(elemento.getPrecio());
            anadir[4] = elemento.getEstado();

            tabla.addRow(anadir);
        }
        this.tablabusqueda.setModel(tabla);
    }

    //Añadimos las citas encontadas a la tabla
    //Recibimos la citas encontradas que no esten cerradas o finalizadas
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbucita = new javax.swing.JPanel();
        batras = new javax.swing.JLabel();
        titulousuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infecha = new javax.swing.JTextField();
        bbuscarfecha = new javax.swing.JLabel();
        inmatricula = new javax.swing.JTextField();
        bbuscarmatricula = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablabusqueda = new javax.swing.JTable();
        inestado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borrar Cita");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        pbucita.setBackground(new java.awt.Color(109, 132, 180));

        batras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/flecha-hacia-la-izquierda.png"))); // NOI18N
        batras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batrasMouseClicked(evt);
            }
        });

        titulousuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulousuarios.setForeground(new java.awt.Color(255, 255, 255));
        titulousuarios.setText("Citas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Búsqueda por fecha");

        infecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infechaActionPerformed(evt);
            }
        });

        bbuscarfecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/busqueda-p.png"))); // NOI18N
        bbuscarfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuscarfechaMouseClicked(evt);
            }
        });

        inmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmatriculaActionPerformed(evt);
            }
        });

        bbuscarmatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/busqueda-p.png"))); // NOI18N
        bbuscarmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuscarmatriculaMouseClicked(evt);
            }
        });

        tablabusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Fecha y hora", "Descripcion", "Precio", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tablabusqueda);

        inestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En proceso", "Finalizado" }));
        inestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inestadoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Búsqueda por matrícula");

        javax.swing.GroupLayout pbucitaLayout = new javax.swing.GroupLayout(pbucita);
        pbucita.setLayout(pbucitaLayout);
        pbucitaLayout.setHorizontalGroup(
            pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbucitaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulousuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(infecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(inmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bbuscarmatricula)
                            .addComponent(bbuscarfecha))))
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(inestado, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(batras))
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pbucitaLayout.setVerticalGroup(
            pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbucitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulousuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batras))
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infecha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pbucitaLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(bbuscarfecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bbuscarmatricula))
                            .addGroup(pbucitaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inestado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbucita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbucita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batrasMouseClicked
        VentanaPrincipal venanaprincipal = new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_batrasMouseClicked

    private void infechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infechaActionPerformed

    }//GEN-LAST:event_infechaActionPerformed

    private void inmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inmatriculaActionPerformed
    /**
     * Botón búsqueda por fecha
     *
     * @param evt
     */
    private void bbuscarfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarfechaMouseClicked
        ArrayList<Cita> encontradas = new ArrayList();
        String fecha = infecha.getText();

        //Recibimos la citas encontradas que no esten cerradas o finalizadas
        encontradas = GestionCitas.consultarCitaFecha(fecha);

        // borramos las citas que no esten en estado pendiente o en proceso
        Iterator<Cita> it = encontradas.iterator();
        while (it.hasNext()) {
            Cita cita = it.next();
            if (!(cita.getEstado().equalsIgnoreCase("pendiente") || cita.getEstado().equalsIgnoreCase("en proceso"))) {
                it.remove();
            }
        }
        //Borramos contanido anterior de la tabla
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i -= 1;
        }

        //Añadimos las citas encontadas a la tabla
        Collections.sort(encontradas);
        for (Cita elemento : encontradas) {
            String anadir[] = new String[5];
            anadir[0] = elemento.getMatricula();
            anadir[1] = elemento.getFechaHora();
            anadir[2] = elemento.getDescripcion();
            anadir[3] = Float.toString(elemento.getPrecio());
            anadir[4] = elemento.getEstado();
            tabla.addRow(anadir);
        }
        this.tablabusqueda.setModel(tabla);
        infecha.setText("");
    }//GEN-LAST:event_bbuscarfechaMouseClicked
    /**
     * Botón búsqueda por matrícula
     *
     * @param evt
     */
    private void bbuscarmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarmatriculaMouseClicked
        ArrayList<Cita> encontradas = new ArrayList();
        String matricula = inmatricula.getText();

        //Recibimos la citas encontradas
        encontradas = GestionCitas.consultarCitaMatricula(matricula);

        // borramos las citas que no esten pendientes o en proceso
        Iterator<Cita> it = encontradas.iterator();
        while (it.hasNext()) {
            Cita cita = it.next();
            if (!(cita.getEstado().equalsIgnoreCase("pendiente") || cita.getEstado().equalsIgnoreCase("en proceso"))) {
                it.remove();
            }
        }

        //Borramos contenido anterior de la tabla
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i -= 1;
        }

        //Añadimos las citas encontadas a la tabla
        Collections.sort(encontradas);
        for (Cita elemento : encontradas) {
            String anadir[] = new String[5];
            anadir[0] = elemento.getMatricula();
            anadir[1] = elemento.getFechaHora();
            anadir[2] = elemento.getDescripcion();
            anadir[3] = Float.toString(elemento.getPrecio());
            anadir[4] = elemento.getEstado();
            tabla.addRow(anadir);
        }
        this.tablabusqueda.setModel(tabla);
        inmatricula.setText("");
    }//GEN-LAST:event_bbuscarmatriculaMouseClicked

    private void inestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inestadoMouseClicked
        // TODO add your handling code here:
        // guardamos la posicion del elemento que vamos a modificar
        int editar = tablabusqueda.getSelectedRow();
        // una vez tenemos la posicion guardamos en una variable cada uno de los atributos de la cita modificada 
        if (editar >= 0) {
            String matricula = Ficheros.citas.get(editar).getMatricula();
            String fecha = Ficheros.citas.get(editar).getFechaHora();
            String descripcion = Ficheros.citas.get(editar).getDescripcion();
            Float precio = Ficheros.citas.get(editar).getPrecio();
            String estado=(String)inestado.getSelectedItem();
            // borramos la cita en la cual tenemos el dato sin modificar 
            GestionCitas.borrarCita(Ficheros.citas.get(editar).getMatricula(), Ficheros.citas.get(editar).getFechaHora());
            // lo borramos tambien de la visualizacion en pantalla 
            tabla.removeRow(editar);
            // creamos una nueva cita y la añadimos al array y al fichero de citas, ya con el valor modificado 
            Cita citaEditada=new Cita(matricula,fecha,descripcion,precio,estado);
            Ficheros.citas.add(citaEditada);
            Ficheros.escribirFicheroCitas();
            //añadimos la cita a la visualizacion en pantalla 
             
            String anadir[] = new String[5];
            anadir[0] = matricula;
            anadir[1] = fecha;
            anadir[2] = descripcion;
            anadir[3] = Float.toString(precio);
            anadir[4] = estado;
            tabla.addRow(anadir);
        
        this.tablabusqueda.setModel(tabla);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario", "Error", 1);
        }


    }//GEN-LAST:event_inestadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display thbbuscarfecha*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batras;
    private javax.swing.JLabel bbuscarfecha;
    private javax.swing.JLabel bbuscarmatricula;
    private javax.swing.JComboBox<String> inestado;
    private javax.swing.JTextField infecha;
    private javax.swing.JTextField inmatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pbucita;
    private javax.swing.JTable tablabusqueda;
    private javax.swing.JLabel titulousuarios;
    // End of variables declaration//GEN-END:variables
}
