/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tallerplus.interfaz;

import com.tallerplus.gestion.GestionCitas;
import com.tallerplus.objetos.Cita;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dani_
 */
public class BuscarCita extends javax.swing.JFrame {
    DefaultTableModel tabla=new DefaultTableModel();
    /**
     * Creates new form BuscarCita
     */
    public BuscarCita() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        //Columnas de la tabla
        tabla.addColumn("Matrícula");
        tabla.addColumn("Fecha y hora");
        tabla.addColumn("Descripción");
        tabla.addColumn("Precio");
        tabla.addColumn("Estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbucita = new javax.swing.JPanel();
        batras = new javax.swing.JLabel();
        titulousuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infecha = new javax.swing.JTextField();
        bbuscarfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inmatricula = new javax.swing.JTextField();
        bbuscarmatricula = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablabusqueda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borrar Cita");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        pbucita.setBackground(new java.awt.Color(109, 132, 180));

        batras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/flecha-hacia-la-izquierda.png"))); // NOI18N
        batras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batrasMouseClicked(evt);
            }
        });

        titulousuarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulousuarios.setForeground(new java.awt.Color(255, 255, 255));
        titulousuarios.setText("Buscar cita");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Búsqueda por fecha");

        infecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infechaActionPerformed(evt);
            }
        });

        bbuscarfecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/busqueda-p.png"))); // NOI18N
        bbuscarfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuscarfechaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Búsqueda por matrícula");

        inmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmatriculaActionPerformed(evt);
            }
        });

        bbuscarmatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tallerplus/icon/busqueda-p.png"))); // NOI18N
        bbuscarmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbuscarmatriculaMouseClicked(evt);
            }
        });

        tablabusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Fecha y hora", "Descripcion", "Precio", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tablabusqueda);

        javax.swing.GroupLayout pbucitaLayout = new javax.swing.GroupLayout(pbucita);
        pbucita.setLayout(pbucitaLayout);
        pbucitaLayout.setHorizontalGroup(
            pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbucitaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pbucitaLayout.createSequentialGroup()
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(infecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bbuscarfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(inmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bbuscarmatricula))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pbucitaLayout.createSequentialGroup()
                        .addComponent(titulousuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batras)))
                .addGap(38, 38, 38))
        );
        pbucitaLayout.setVerticalGroup(
            pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbucitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulousuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batras))
                .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infecha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbucitaLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(bbuscarfecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbucitaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pbucitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pbucitaLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pbucitaLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(bbuscarmatricula)))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbucita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbucita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batrasMouseClicked
        VentanaPrincipal venanaprincipal=new VentanaPrincipal();
        dispose();
    }//GEN-LAST:event_batrasMouseClicked

    private void infechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infechaActionPerformed

    }//GEN-LAST:event_infechaActionPerformed

    private void inmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inmatriculaActionPerformed
/**
 * Botón búsqueda por fecha
 * @param evt 
 */
    private void bbuscarfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarfechaMouseClicked
        ArrayList<Cita> encontradas=new ArrayList();
        String fecha=infecha.getText();
        
        //Recibimos la citas encontradas
        encontradas=GestionCitas.consultarCitaFecha(fecha);
        
        //Borramos contanido anterior de la tabla
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i-=1;
        }
        
        //Añadimos las citas encontadas a la tabla
        for(Cita elemento: encontradas){
            String anadir[]=new String [5];
            anadir[0]=elemento.getMatricula();
            anadir[1]=elemento.getFechaHora();
            anadir[1]=elemento.getDescripcion();
            anadir[3]=Float.toString(elemento.getPrecio());
            anadir[4]=elemento.getEstado();
            System.out.println(anadir);
            tabla.addRow(anadir);
        }
        this.tablabusqueda.setModel(tabla);
    }//GEN-LAST:event_bbuscarfechaMouseClicked
/**
 * Botón búsqueda por matrícula
 * @param evt 
 */
    private void bbuscarmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbuscarmatriculaMouseClicked
        ArrayList<Cita> encontradas=new ArrayList();
        String matricula=inmatricula.getText();
        
        //Recibimos la citas encontradas
        encontradas=GestionCitas.consultarCitaMatricula(matricula);
        
        //Borramos contenido anterior de la tabla
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i-=1;
        }
        
        //Añadimos las citas encontadas a la tabla
        for(Cita elemento: encontradas){
            String anadir[]=new String [5];
            anadir[0]=elemento.getMatricula();
            anadir[1]=elemento.getFechaHora();
            anadir[1]=elemento.getDescripcion();
            anadir[3]=Float.toString(elemento.getPrecio());
            anadir[4]=elemento.getEstado();
            tabla.addRow(anadir);
        }
        this.tablabusqueda.setModel(tabla);
    }//GEN-LAST:event_bbuscarmatriculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display thbbuscarfecha*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batras;
    private javax.swing.JLabel bbuscarfecha;
    private javax.swing.JLabel bbuscarmatricula;
    private javax.swing.JTextField infecha;
    private javax.swing.JTextField inmatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pbucita;
    private javax.swing.JTable tablabusqueda;
    private javax.swing.JLabel titulousuarios;
    // End of variables declaration//GEN-END:variables
}
